extends "res://AsteroidSpawner.gd"

func _init():
	objectClass[-1] = {
		"Fo":[ # Forsterite
			preload("res://RealisticMinerals/asteroids/mineral-fo-1.tscn"),
			preload("res://RealisticMinerals/asteroids/mineral-fo-2.tscn"),
			preload("res://RealisticMinerals/asteroids/mineral-fo-3.tscn"),
			preload("res://RealisticMinerals/asteroids/mineral-fo-4.tscn"),
			preload("res://RealisticMinerals/asteroids/mineral-fo-5.tscn"),
			preload("res://RealisticMinerals/asteroids/mineral-fo-6.tscn"),
			preload("res://RealisticMinerals/asteroids/mineral-fo-7.tscn"),
		],
		"Fa":[ # Fayalite
			preload("res://RealisticMinerals/asteroids/mineral-fa-1.tscn"),
			preload("res://RealisticMinerals/asteroids/mineral-fa-2.tscn"),
			preload("res://RealisticMinerals/asteroids/mineral-fa-3.tscn"),
			preload("res://RealisticMinerals/asteroids/mineral-fa-4.tscn"),
			preload("res://RealisticMinerals/asteroids/mineral-fa-5.tscn"),
			preload("res://RealisticMinerals/asteroids/mineral-fa-6.tscn"),
			preload("res://RealisticMinerals/asteroids/mineral-fa-7.tscn"),
		],
		"Di":[ # Diopside
			preload("res://RealisticMinerals/asteroids/mineral-di-1.tscn"),
			preload("res://RealisticMinerals/asteroids/mineral-di-2.tscn"),
			preload("res://RealisticMinerals/asteroids/mineral-di-3.tscn"),
			preload("res://RealisticMinerals/asteroids/mineral-di-4.tscn"),
			preload("res://RealisticMinerals/asteroids/mineral-di-5.tscn"),
			preload("res://RealisticMinerals/asteroids/mineral-di-6.tscn"),
			preload("res://RealisticMinerals/asteroids/mineral-di-7.tscn"),
		],
		"Jd":[ # Jadeite
			preload("res://RealisticMinerals/asteroids/mineral-jd-1.tscn"),
			preload("res://RealisticMinerals/asteroids/mineral-jd-2.tscn"),
			preload("res://RealisticMinerals/asteroids/mineral-jd-3.tscn"),
			preload("res://RealisticMinerals/asteroids/mineral-jd-4.tscn"),
			preload("res://RealisticMinerals/asteroids/mineral-jd-5.tscn"),
			preload("res://RealisticMinerals/asteroids/mineral-jd-6.tscn"),
			preload("res://RealisticMinerals/asteroids/mineral-jd-7.tscn"),
		],
		"Jhn":[ # Johannsenite
			preload("res://RealisticMinerals/asteroids/mineral-jhn-1.tscn"),
			preload("res://RealisticMinerals/asteroids/mineral-jhn-2.tscn"),
			preload("res://RealisticMinerals/asteroids/mineral-jhn-3.tscn"),
			preload("res://RealisticMinerals/asteroids/mineral-jhn-4.tscn"),
			preload("res://RealisticMinerals/asteroids/mineral-jhn-5.tscn"),
			preload("res://RealisticMinerals/asteroids/mineral-jhn-6.tscn"),
			preload("res://RealisticMinerals/asteroids/mineral-jhn-7.tscn"),
		],
		"Kos":[ # Kosmochlor
			preload("res://RealisticMinerals/asteroids/mineral-kos-1.tscn"),
			preload("res://RealisticMinerals/asteroids/mineral-kos-2.tscn"),
			preload("res://RealisticMinerals/asteroids/mineral-kos-3.tscn"),
			preload("res://RealisticMinerals/asteroids/mineral-kos-4.tscn"),
			preload("res://RealisticMinerals/asteroids/mineral-kos-5.tscn"),
			preload("res://RealisticMinerals/asteroids/mineral-kos-6.tscn"),
			preload("res://RealisticMinerals/asteroids/mineral-kos-7.tscn"),
		],
		"Nms":[ # Namansilite
			preload("res://RealisticMinerals/asteroids/mineral-nms-1.tscn"),
			preload("res://RealisticMinerals/asteroids/mineral-nms-2.tscn"),
			preload("res://RealisticMinerals/asteroids/mineral-nms-3.tscn"),
			preload("res://RealisticMinerals/asteroids/mineral-nms-4.tscn"),
			preload("res://RealisticMinerals/asteroids/mineral-nms-5.tscn"),
			preload("res://RealisticMinerals/asteroids/mineral-nms-6.tscn"),
			preload("res://RealisticMinerals/asteroids/mineral-nms-7.tscn"),
		],
		"Nta":[ # Natalyite
			preload("res://RealisticMinerals/asteroids/mineral-nta-1.tscn"),
			preload("res://RealisticMinerals/asteroids/mineral-nta-2.tscn"),
			preload("res://RealisticMinerals/asteroids/mineral-nta-3.tscn"),
			preload("res://RealisticMinerals/asteroids/mineral-nta-4.tscn"),
			preload("res://RealisticMinerals/asteroids/mineral-nta-5.tscn"),
			preload("res://RealisticMinerals/asteroids/mineral-nta-6.tscn"),
			preload("res://RealisticMinerals/asteroids/mineral-nta-7.tscn"),
		],
		"Spd":[ # Spodumene
			preload("res://RealisticMinerals/asteroids/mineral-spd-1.tscn"),
			preload("res://RealisticMinerals/asteroids/mineral-spd-2.tscn"),
			preload("res://RealisticMinerals/asteroids/mineral-spd-3.tscn"),
			preload("res://RealisticMinerals/asteroids/mineral-spd-4.tscn"),
			preload("res://RealisticMinerals/asteroids/mineral-spd-5.tscn"),
			preload("res://RealisticMinerals/asteroids/mineral-spd-6.tscn"),
			preload("res://RealisticMinerals/asteroids/mineral-spd-7.tscn"),
		],
		"Ens":[ # Enstatite
			preload("res://RealisticMinerals/asteroids/mineral-ens-1.tscn"),
			preload("res://RealisticMinerals/asteroids/mineral-ens-2.tscn"),
			preload("res://RealisticMinerals/asteroids/mineral-ens-3.tscn"),
			preload("res://RealisticMinerals/asteroids/mineral-ens-4.tscn"),
			preload("res://RealisticMinerals/asteroids/mineral-ens-5.tscn"),
			preload("res://RealisticMinerals/asteroids/mineral-ens-6.tscn"),
			preload("res://RealisticMinerals/asteroids/mineral-ens-7.tscn"),
		],
		"Qz":[ # Quartz
			preload("res://RealisticMinerals/asteroids/mineral-qz-1.tscn"),
			preload("res://RealisticMinerals/asteroids/mineral-qz-2.tscn"),
			preload("res://RealisticMinerals/asteroids/mineral-qz-3.tscn"),
			preload("res://RealisticMinerals/asteroids/mineral-qz-4.tscn"),
			preload("res://RealisticMinerals/asteroids/mineral-qz-5.tscn"),
			preload("res://RealisticMinerals/asteroids/mineral-qz-6.tscn"),
			preload("res://RealisticMinerals/asteroids/mineral-qz-7.tscn"),
		],
		"Crs":[ # Cristobalite
			preload("res://RealisticMinerals/asteroids/mineral-crs-1.tscn"),
			preload("res://RealisticMinerals/asteroids/mineral-crs-2.tscn"),
			preload("res://RealisticMinerals/asteroids/mineral-crs-3.tscn"),
			preload("res://RealisticMinerals/asteroids/mineral-crs-4.tscn"),
			preload("res://RealisticMinerals/asteroids/mineral-crs-5.tscn"),
			preload("res://RealisticMinerals/asteroids/mineral-crs-6.tscn"),
			preload("res://RealisticMinerals/asteroids/mineral-crs-7.tscn"),
		],
		"Trd":[ # Tridymite
			preload("res://RealisticMinerals/asteroids/mineral-trd-1.tscn"),
			preload("res://RealisticMinerals/asteroids/mineral-trd-2.tscn"),
			preload("res://RealisticMinerals/asteroids/mineral-trd-3.tscn"),
			preload("res://RealisticMinerals/asteroids/mineral-trd-4.tscn"),
			preload("res://RealisticMinerals/asteroids/mineral-trd-5.tscn"),
			preload("res://RealisticMinerals/asteroids/mineral-trd-6.tscn"),
			preload("res://RealisticMinerals/asteroids/mineral-trd-7.tscn"),
		],
		"Ab":[ # Albite
			preload("res://RealisticMinerals/asteroids/mineral-ab-1.tscn"),
			preload("res://RealisticMinerals/asteroids/mineral-ab-2.tscn"),
			preload("res://RealisticMinerals/asteroids/mineral-ab-3.tscn"),
			preload("res://RealisticMinerals/asteroids/mineral-ab-4.tscn"),
			preload("res://RealisticMinerals/asteroids/mineral-ab-5.tscn"),
			preload("res://RealisticMinerals/asteroids/mineral-ab-6.tscn"),
			preload("res://RealisticMinerals/asteroids/mineral-ab-7.tscn"),
		],
		"An":[ # Anorthite
			preload("res://RealisticMinerals/asteroids/mineral-an-1.tscn"),
			preload("res://RealisticMinerals/asteroids/mineral-an-2.tscn"),
			preload("res://RealisticMinerals/asteroids/mineral-an-3.tscn"),
			preload("res://RealisticMinerals/asteroids/mineral-an-4.tscn"),
			preload("res://RealisticMinerals/asteroids/mineral-an-5.tscn"),
			preload("res://RealisticMinerals/asteroids/mineral-an-6.tscn"),
			preload("res://RealisticMinerals/asteroids/mineral-an-7.tscn"),
		],
		"Or":[ # Orthoclase
			preload("res://RealisticMinerals/asteroids/mineral-or-1.tscn"),
			preload("res://RealisticMinerals/asteroids/mineral-or-2.tscn"),
			preload("res://RealisticMinerals/asteroids/mineral-or-3.tscn"),
			preload("res://RealisticMinerals/asteroids/mineral-or-4.tscn"),
			preload("res://RealisticMinerals/asteroids/mineral-or-5.tscn"),
			preload("res://RealisticMinerals/asteroids/mineral-or-6.tscn"),
			preload("res://RealisticMinerals/asteroids/mineral-or-7.tscn"),
		],
	}
